// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/tenant/{tenant_id}/health": {
            "get": {
                "description": "Returns the composite health score, signal metrics, and auto-generated OTel remediation for a given tenant.",
                "produces": [
                    "application/json"
                ],
                "summary": "Get Health Metrics for a Tenant",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tenant UUID",
                        "name": "tenant_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.HealthResponse"
                        }
                    },
                    "400": {
                        "description": "invalid path",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "rest.HealthResponse": {
            "type": "object",
            "properties": {
                "healthScore": {
                    "type": "number"
                },
                "metrics": {
                    "$ref": "#/definitions/rest.MetricsPayload"
                },
                "remediation": {
                    "$ref": "#/definitions/rest.RemediationPayload"
                }
            }
        },
        "rest.MetricValue": {
            "type": "object",
            "properties": {
                "change": {
                    "type": "number"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "rest.MetricsPayload": {
            "type": "object",
            "properties": {
                "cardinality": {
                    "$ref": "#/definitions/rest.MetricValue"
                },
                "coverage": {
                    "$ref": "#/definitions/rest.MetricValue"
                },
                "orphans": {
                    "$ref": "#/definitions/rest.MetricValue"
                }
            }
        },
        "rest.RemediationPayload": {
            "type": "object",
            "properties": {
                "issueType": {
                    "type": "string"
                },
                "yaml": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "TelemetryHealth API",
	Description:      "REST API for TelemetryHealth control plane",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
